name:                aoc2019
version:             0.1.0.0
github:              "jlavelle/aoc"
license:             BSD3
author:              "John C. Lavelle"
maintainer:          "jlavelle604@gmail.com"
copyright:           "2019 John C. Lavelle"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jlavelle/aoc/aoc-2019>

dependencies:
- base >= 4.7 && < 5
- text
- bytestring
- containers
- microlens
- semialign
- these
- recursion-schemes
- algebraic-graphs
- criterion
- comonad
- foldl
- profunctors
- mtl
- hashable
- linear
- free
- lens
- megaparsec
- monoidal-containers
- witherable

default-extensions:
- LambdaCase
- BlockArguments
- OverloadedStrings
- FlexibleContexts
- TupleSections
- ViewPatterns
- DeriveGeneric
- StandaloneDeriving
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- DerivingStrategies
- GeneralizedNewtypeDeriving
- ConstraintKinds
- ScopedTypeVariables
- KindSignatures
- TypeFamilies

library:
  source-dirs: src

executables:
  aoc2019-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2019

tests:
  aoc2019-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc2019
